[dependencies]
base = "0.14.1"

[package]
name = "glob"
version = "0.0.1"
description = "A simple glob pattern matching library"
repository = "https://github.com/edjcase/motoko_glob"
keywords = ["glob", "pattern", "matching", "file", "directory", "path"]
license = "MIT"

[dev-dependencies]
test = "2.0.0"
